### ISSUE TITLE
the-letter-space

### ISSUE THREAD

**Issue by awolden** [kesne/letters#1]
It is confusing to have a module called `the-letter-space` because space isn't really a letter by any definition. I would politely request that we change the name of that module to `the-whitespace-space` or `the-syntax-space`.

Thanks for the taking the time to read this issue,
Alex

**Comment by jquatier** [comment]
Can we keep `the-letter-space` as a supported and actively maintained module for backwards compatibility? I already pulled it into my production app.

Warm regards,
JQ

**Comment by awolden** [comment]
+1 on the backwards compatibility thinking. Maybe syntax/whitespace unicode characters should be broken into their own monorepo `whitespace` or `syntax` that way this repo can stay untouched

**Comment by kesne** [comment]
@awolden Thanks for the feedback! What do you think about renaming all of the packages to `the-character-*`? I think having a consistent prefix is desirable. The uppercase packages could then be `the-uppercase-character-*`.

@jquatier Don't worry, any package rename would be backwards compat.

**Comment by kesne** [comment]
@awolden @jquatier I renamed this repo and renamed the packages. They're now available as `@characters/*`.
