### ISSUE TITLE
"Case" constructor option

### ISSUE THREAD

**Issue by dugword** [kesne/letters#2]
I am trying to use this module in my production application, but sometimes I need an uppercase letter. Is that a feature you can add, preferably as a constructor option when initializing the modules?

Thanks,

Doug

**Comment by kesne** [comment]
@dugword Thanks for the feedback! I was planning on publishing uppercase variants of all of the packages.

**Comment by kesne** [comment]
@dugword Published new packages as `@characters/*-uppercase`
